#!/bin/bash
bspc config border_width         3
bspc config window_gap           12

bspc monitor -d "i" "ii" "iii" "iv" "v" "vi"

bspc config top_padding 4
bspc config left_padding 4
bspc config right_padding 4
bspc config bottom_padding 4

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#333333"
bspc config focused_border_color "#5b6e75"
bspc config presel_border_color "#66cc66"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.0


# Rules
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a gimp follow=on floating=on

# Exec on start
${HOME}/.config/bspwm/panel
